spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/employee?characterEncoding=utf-8&serverTimezone=UTC&useSSL=false
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    max-idle: 10
    max-wait: 10000
  freemarker:
    cache: false
    template-loader-path: classpath:/templates/

emp:
  is-dev: true
  dev-server-port: 8089

mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  typeAliasesPackage: com.emp.**.entity
  configuration:
    map-underscore-to-camel-case: true
    cache-enabled: false
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8099
  # tomcat:
  #   uri-encoding: utf-8
  #   servlet:
  #     session:
  #       tracking-modes: cookie
